package com.yehyun.memo.notepad.domain.member;

import jakarta.persistence.*;
import lombok.Data;

//CREATE TABLE member (
//        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        name VARCHAR(100) NOT NULL,
//login_id VARCHAR(50) NOT NULL UNIQUE,
//password VARCHAR(255) NOT NULL
//);

@Data
@Entity
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @Column(unique = true)
    private String loginId;
    private String password;
    private String role;

    public Member() {
    }

    public Member(String name, String loginId, String password) {
        this.name = name;
        this.loginId = loginId;
        this.password = password;
        this.role = "ROLE_USER";
    }

    public boolean isPasswordMatch(String rawPassword) {
        return password.equals(rawPassword);
    }
}
