package com.yehyun.memo.notepad.domain.member;

import jakarta.persistence.*;
import lombok.Data;

//CREATE TABLE member (
//        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        name VARCHAR(100) NOT NULL,
//login_id VARCHAR(50) NOT NULL UNIQUE,
//password VARCHAR(255) NOT NULL
//);

@Data
@Entity
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @Column(unique = true)
    private String loginId;

    @Column(nullable = true)
    private String password;
    private String role;

    private String provider;
    private String providerId;

    public Member() {
    }

    public Member(String name, String loginId, String role) {
        this.name = name;
        this.loginId = loginId;
        this.role = role;
    }

    public boolean isGuest() {
        return "ROLE_GUEST".equals(role);
    }
}
