package com.yehyun.memo.notepad.domain.member;

import jakarta.persistence.*;
import lombok.Data;

//CREATE TABLE member (
//        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        name VARCHAR(100) NOT NULL,
//login_id VARCHAR(50) NOT NULL UNIQUE,
//password VARCHAR(255) NOT NULL
//);

@Data
@Entity
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @Column(unique = true)
    private String loginId;

    private String password;
    private String role;

    private String provider;
    private String providerId;

    public Member() {
    }

    private Member(String name, String loginId, String password, String role) {
        this.name = name;
        this.loginId = loginId;
        this.password = password;
        this.role = role;
    }

    private Member(String name, String loginId, String password, String role, String provider, String providerId) {
        this.name = name;
        this.loginId = loginId;
        this.password = password;
        this.role = role;
        this.provider = provider;
        this.providerId = providerId;
    }

    public static Member ofLocal(String name, String loginId, String password, String role) {
        return new Member(name, loginId, password, role);
    }

    public static Member ofOAuth(String name, String loginId, String password, String role, String provider, String providerId) {
        return new Member(name, loginId, password, role, provider, providerId);
    }
}
