spring:
  profiles:
    active: prod

  application:
    name: notepad

  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

server:
  address: 0.0.0.0
  port: ${server.port:8284}
